/**
 * /api/email — sends a Dearly note as an email via Resend.
 *
 * POST body:
 *   {
 *     to:            string  required  recipient email address
 *     fromName:      string  required  sender's display name (from the note)
 *     recipientName: string  optional  recipient's name (for greeting + subject)
 *     shareUrl:      string  required  the share URL to embed in the body
 *     personalNote:  string  optional  user-added note (above the link)
 *     subject:       string  optional  user-supplied / pre-generated subject;
 *                                      falls back to a contextual template
 *                                      if absent or blank
 *   }
 *
 * Env vars:
 *   RESEND_API_KEY  required  https://resend.com/api-keys
 *   EMAIL_FROM      optional  "Dearly <noreply@yourdomain.com>"
 *                             defaults to Resend's "onboarding@resend.dev"
 *                             which only works for testing — for production
 *                             you must verify a domain in Resend.
 *   PUBLIC_ORIGIN   optional  Where assets like the blurred background live.
 *                             Defaults to https://bhanu-dearly.vercel.app.
 *
 * Response:
 *   200  { ok: true,  id: <resend_message_id> }
 *   4xx  { ok: false, error: '...' }
 *   5xx  { ok: false, error: '...' }
 */

import { buildEmailHtml, buildEmailText } from '../src/lib/emailTemplate.js'

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

function badRequest(res, msg) {
  res.statusCode = 400
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ ok: false, error: msg }))
}

function serverError(res, msg) {
  res.statusCode = 500
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ ok: false, error: msg }))
}

// First name only — "Marcus Aurelius" → "Marcus". Used only by the
// template fallback subject below; the email body's firstName logic
// lives inside src/lib/emailTemplate.js.
function firstName(name) {
  if (!name) return ''
  return String(name).trim().split(/\s+/)[0] || ''
}

// (HTML + plain-text body builders moved to src/lib/emailTemplate.js
// so the in-app preview and this server route share one source of truth.)

// Template subject for when the client didn't pre-generate one (e.g.
// the suggest-subject endpoint failed and the form was sent anyway).
// Mirrors the fallback logic in /api/suggest-subject.
function templateSubject({ fromName, recipientName }) {
  const who  = (firstName(recipientName) || '').trim()
  const from = (firstName(fromName) || fromName || 'Someone').trim()
  if (who) return `Hey ${who}, ${from} wrote you a personal note`
  return       `${from} wrote you a personal note on Dearly`
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.statusCode = 405
    res.setHeader('Allow', 'POST')
    res.end()
    return
  }

  let body = ''
  for await (const chunk of req) body += chunk
  let payload
  try { payload = JSON.parse(body) }
  catch { return badRequest(res, 'Invalid JSON body') }

  // Recipients: accept either a single string or an array of strings.
  // Dedupe + validate each. Hard-cap at 5 to match the client; protects
  // the Resend free tier from a runaway client bug.
  const MAX_RECIPIENTS = 5
  const rawTo = payload.to
  let recipients = []
  if (typeof rawTo === 'string') {
    recipients = rawTo.split(/[\s,;]+/).map(s => s.trim()).filter(Boolean)
  } else if (Array.isArray(rawTo)) {
    recipients = rawTo.map(s => String(s ?? '').trim()).filter(Boolean)
  }
  recipients = Array.from(new Set(recipients.map(r => r.toLowerCase())))
  if (recipients.length === 0)                return badRequest(res, 'At least one recipient email is required.')
  if (recipients.length > MAX_RECIPIENTS)     return badRequest(res, `Too many recipients — keep it to ${MAX_RECIPIENTS} or fewer.`)
  const invalid = recipients.find(r => !EMAIL_RE.test(r))
  if (invalid)                                 return badRequest(res, `"${invalid}" is not a valid email.`)

  const fromName      = (payload.fromName      ?? '').trim().slice(0, 60) || 'Someone'
  const recipientName = (payload.recipientName ?? '').trim().slice(0, 60)
  const shareUrl      = (payload.shareUrl      ?? '').trim()
  const personalNote  = (payload.personalNote  ?? '').trim().slice(0, 500)
  // Subject: pre-generated by /api/suggest-subject and (optionally) edited
  // by the user in the ShareSheet. Falls back to a template if absent or
  // blank — never trust the client to always send one.
  const subject = (payload.subject ?? '').trim().slice(0, 160)
                || templateSubject({ fromName, recipientName })

  if (!shareUrl)                   return badRequest(res, 'shareUrl is required.')
  if (!/^https?:\/\//i.test(shareUrl)) return badRequest(res, 'shareUrl must be a http(s) URL.')

  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) return serverError(res, 'Email service is not configured (RESEND_API_KEY missing).')

  // "Dearly <onboarding@resend.dev>" works out of the box on Resend's sandbox
  // for testing — but only sends to the email you signed up with. For prod,
  // verify a domain at https://resend.com/domains and set EMAIL_FROM.
  const fromAddress = process.env.EMAIL_FROM || 'Dearly <onboarding@resend.dev>'

  // Asset origin for the blurred bg image. Production deploys default to
  // the canonical URL; can be overridden per-deploy via PUBLIC_ORIGIN.
  const assetOrigin = (process.env.PUBLIC_ORIGIN || 'https://dearlynotes.app').replace(/\/$/, '')

  // Build the bodies once (identical content per recipient — only the
  // `to` field changes). Pre-building avoids re-doing the HTML/text work
  // five times in the loop.
  const html = buildEmailHtml({ fromName, recipientName, shareUrl, personalNote, assetOrigin })
  const text = buildEmailText({ fromName, recipientName, shareUrl, personalNote })

  // Send one PRIVATE email per recipient (not a single email with all
  // addresses in the TO header). Recipients don't see each other's
  // addresses — important for personal notes. Promise.allSettled so a
  // single bounce doesn't sink the others.
  try {
    const results = await Promise.allSettled(recipients.map(to =>
      fetch('https://api.resend.com/emails', {
        method:  'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type':  'application/json',
        },
        body: JSON.stringify({ from: fromAddress, to, subject, html, text }),
      }).then(async r => {
        if (!r.ok) {
          const errText = await r.text()
          throw new Error(`${r.status}: ${errText.slice(0, 160)}`)
        }
        return r.json()
      })
    ))

    const sent     = results.filter(r => r.status === 'fulfilled').map((r, i) => recipients[i])
    const failures = results
      .map((r, i) => ({ r, addr: recipients[i] }))
      .filter(({ r }) => r.status === 'rejected')
      .map(({ r, addr }) => ({ addr, reason: r.reason?.message || 'send failed' }))

    res.statusCode = sent.length > 0 ? 200 : 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({
      ok:       sent.length > 0,
      sent:     sent.length,
      failed:   failures.length,
      failures, // [{ addr, reason }, ...] — empty array on full success
      error:    sent.length === 0
        ? `All ${failures.length} sends failed. First reason: ${failures[0]?.reason}`
        : undefined,
    }))
  } catch (e) {
    return serverError(res, e.message || 'Failed to send email.')
  }
}
